{% set name = "pyadi-iio" %}
{% set version = "0.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # url: "https://github.com/analogdevicesinc/{{ name }}/archive/v{{ version }}.tar.gz"
  url: https://github.com/analogdevicesinc/pyadi-iio/archive/master.zip
  #sha256: e6d40f07ecd1838a5b2609f6a74c130bbc0c6dfb67b6039ea6d61b21fe8b76bc

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - numpy
    - pip
    - python

  run:
    - numpy
    - libiio
    - python

test:
  imports:
    - adi

about:
  home: "https://github.com/analogdevicesinc/pyadi-iio"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "Interfaces to stream data from ADI hardware"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - petrushy
