{% set name = "pyadi-iio" %}
{% set version = "0.0.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/analogdevicesinc/{{ name }}/archive/v{{ version }}.tar.gz"
  sha256: bad27a4a425837c43cf1eb623b2c015f4cfecc6dbe57b875fb4edf04c05b7e44

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - numpy
    - pip
    - python

  run:
    - numpy
    - libiio
    - python

test:
  imports:
    - adi

about:
  home: "https://github.com/analogdevicesinc/pyadi-iio"
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "Interfaces to stream data from ADI hardware"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - petrushy
