package:
  name: scipy-lecture-notes-doc
  version: "2017.1"

source:
  fn: sscipy-lectures-scipy-lectures.github.com-a07c1bb.zip
  url: https://github.com/scipy-lectures/scipy-lectures.github.com/zipball/master
  md5: 514d33578bc056afbaff987c065dc4da

build:
  noarch: generic
  number: 0

about:
  home: https://scipy-lectures.github.io/
  license: http://creativecommons.org/licenses/by/3.0/us

