package:
  name: orekit-doc
  version: '7.0'



build:

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1
  # Builds:
  # 1 - orekit 7.0 development version


requirements:
  build:

  run:


about:
  home: hhttps://www.orekit.org/
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
