package:
  name: traits-enaml
  version: "0.3.0.dev0"

source:
  #fn: traits-enaml-0.2.1.tar.gz
  #url: https://pypi.python.org/packages/source/t/traits-enaml/traits-enaml-0.2.1.tar.gz
  #md5: 5b59f54e6b1cd01644c4f5fcb2c5762f
  #fn: master.zip
  git_url: https://github.com/enthought/traits-enaml.git
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - traits-enaml = traits-enaml:main
    #
    # Would create an entry point called traits-enaml that calls traits-enaml.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  requires:
  - traits
  - enaml

  imports:
    - traits_enaml
    - traits_enaml.testing
    - traits_enaml.testing.tests
    - traits_enaml.tests
    - traits_enaml.widgets

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/enthought/traits-enaml
  license: UNKNOWN
  summary: 'Utilities for interoperation between Traits and Enaml'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
