package:
  name: matplotlib-doc
  version: 1.4.3

source:
  fn: matplotlib-1.4.3.tar.gz
  url: http://sourceforge.net/projects/matplotlib/files/matplotlib/matplotlib-1.4.3/matplotlib-1.4.3.tar.gz/download
  #md5: 444624ad58de05f9029b0b5811e11c17
  patches:


build:
  noarch: True
  number: 0

requirements:
  build:
    - numpy
    - dateutil
    - freetype
    - nose
    - pyparsing
    - pytz
    - tornado
    - libpng
    - matplotlib 1.4.0
    - numpydoc
    - pygments

  run:

about:
  home: http://matplotlib.sourceforge.net/
  license: PSF-based (http://matplotlib.sourceforge.net/users/license.html)
