package:
  name: pandas-doc
  version: '0.18.1'

source:
  fn: pandas.zip
  url: http://pandas.pydata.org/pandas-docs/version/0.18.1/pandas.zip
  md5: 60290b819c1a247b56eed31a2974dcfd
  patches:


#build:
#  noarch: True
#  number: 0

requirements:
  build:

  run:

about:
  home: http://pandas.pydata.org
  license: http://pandas.pydata.org/pandas-docs/stable/overview.html#license
