package:
  name: hexdump
  version: "3.2"

source:
  fn: hexdump-3.2.zip
  url: https://pypi.python.org/packages/source/h/hexdump/hexdump-3.2.zip
  md5: ec61fc2d8ff11d3ab096c0249cf52db9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - hexdump = hexdump:main
    #
    # Would create an entry point called hexdump that calls hexdump.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://bitbucket.org/techtonik/hexdump/
  license: Public Domain
  summary: 'view/edit your binary with any text editor'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
