package:
  name: numpy-doc
  version: '1.13.0'

source:
  fn: numpy-html-1.13.0.zip
  url: https://docs.scipy.org/doc/numpy/numpy-html-1.13.0.zip
  md5: 9e3a32f4babcc269d45850615aedbe61

build:
  noarch: generic
  number: 0

about:
  home: http://docs.scipy.org
  license:
