package:
  name: enaml-doc
  version: '0.9.1'

source:
  #fn: sympy-0.7.5/sympy-docs-html-0.7.5.zip
  #url: https://github.com/sympy/sympy/releases/download/sympy-0.7.5/sympy-docs-html-0.7.5.zip
  patches:


#build:
#  noarch: True
#  number: 0

requirements:
  build:

  run:

about:
  home: http://nucleic.github.io/enaml/doc
  license:
