package:
  name: ulmo
  version: "0.7.4"

source:
  fn: ulmo-0.7.4.tar.gz
  url: https://pypi.python.org/packages/source/u/ulmo/ulmo-0.7.4.tar.gz
  md5: 9c9eec18b85691dc177c03158f7c850e
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ulmo = ulmo:main
    #
    # Would create an entry point called ulmo that calls ulmo.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - lxml
    - numpy
    - pandas
    - pytables
    - setuptools

  run:
    - python
    - lxml
    - numpy
    - pandas
    - pytables

test:
  # Python imports
  imports:
    - ulmo.usgs.nwis
    - ulmo.cdec.historical
    - ulmo.util
    - ulmo.waterml
    - ulmo.ncdc
    - ulmo.cpc
    - ulmo.cuahsi
    - ulmo.cpc.drought
    - ulmo.ncdc.gsod
    - ulmo.usgs.eddn
    - ulmo.ncdc.cirs
    - ulmo.twc
    - ulmo.cuahsi.his_central
    - ulmo.usgs
    - ulmo.usace.rivergages
    - ulmo
    - ulmo.ncdc.ghcn_daily
    - ulmo.usace.swtwc
    - ulmo.twc.kbdi
    - ulmo.cuahsi.wof
    - ulmo.usace
    - ulmo.cdec

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/twdb/ulmo/
  license: BSD License
  summary: 'clean, simple and fast access to public hydrology and climatology data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
