package:
  name: jcc
  version: "2.21"

source:
  # fn: JCC-2.21.tar.gz
  #url: https://pypi.python.org/packages/source/J/JCC/JCC-2.21.tar.gz#md5=18772811c1c9181e6f7512169828f840
  #md5: 18772811c1c9181e6f7512169828f840             # (optional)
  svn_url: http://svn.apache.org/repos/asf/lucene/pylucene/trunk/jcc
  svn_rev: 1751160
  svn_ignore_externals: True # (defaults to no)

  # Patches may optionally be applied to the source
  patches:
    - setup.patch # [win]   # Make windows type separators

build:
  number: 2
  #binary_relocation: False

  rpaths:
    - lib
    - jre/lib/amd64/
    - jre/lib/amd64/server/

  # A regular expression describing files to not install using soft
  # links. If hard links are not possible and this is set, the package
  # will be installed via copying. By default all files are considered
  # safe for soft linking.
  # no_softlink: (lib/site-packages/jcc) # Don't softlink bin/path1.py or bin/path2



  #detect_binary_files_with_prefix: True

  has_prefix_files:
    - lib/python2.7/site-packages/jcc/config.py # [linux]

  #binary_has_prefix_files:
  #  - lib/python2.7/site-packages/jcc/_jcc.so # [linux]
  #  - lib/python2.7/site-packages/libjcc.so # [linux]


requirements:
  build:
    - python
    - java-jdk
    #- setuptools

  run:
    - python
    - java-jdk

test:
  imports:
    - jcc

  files:
    - test/myrun_test.py

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - python myrun_test.py

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
